// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android app from google-services.json (br.app.arrow.driver).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjWM-AAnyO_quYy6_NnMcysURH2SSogw',
    appId: '1:661081769489:android:7eea7bece5a655cfa4d3b3',
    messagingSenderId: '661081769489',
    projectId: 'j-arrow',
    databaseURL: 'https://j-arrow-default-rtdb.firebaseio.com',
    storageBucket: 'j-arrow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjWM-AAnyO_quYy6_NnMcysURH2SSogw',
    appId: '1:661081769489:web:7eea7bece5a655cfa4d3b0',
    messagingSenderId: '661081769489',
    projectId: 'j-arrow',
    databaseURL: 'https://j-arrow-default-rtdb.firebaseio.com',
    storageBucket: 'j-arrow.firebasestorage.app',
    iosBundleId: 'br.app.arrow.driver',
  );
}
